services:
  mysql:
    image: mysql:8.4
    container_name: week4-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: week4_db
      TZ: Asia/Shanghai
    ports:
      - "3307:3306"
    volumes:
      - week4-mysql-data:/var/lib/mysql

volumes:
  week4-mysql-data:
